global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'energy-meter'
    static_configs:
      - targets: ['cwl9h7shnk.execute-api.ap-south-1.amazonaws.com']
    scheme: https
    metrics_path: /dev/metrics